=== danielamadori/Simulator-BPMN-CPI/docs/schemas/general/bpmn/region.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "region.schema.json",
  "title": "Region tree representing BPMN elements",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for region"
    },
    "type": {
      "type": "string",
      "enum": ["choice", "parallel", "sequence", "loop", "nature"]
    },
    "label": {
      "type": "string",
      "description": "Label for the region, used for display purposes."
    },
    "duration": {
      "type": "number",
      "description": "Duration associated with the region, if applicable."
    },
    "impacts": {
      "type": "array",
      "items": {
        "type": "number",
        "description": "Identifier of the impact associated with this region.",
        "minimum": 0
      },
      "description": "Vector of impacts associated with the region."
    },
    "children": {
      "type": "array",
      "items": { "$ref": "#" },
      "description": "List of child regions or tasks within this region."
    },
    "distribution": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      }
    }
  },
  "required": [
    "id",
    "type"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "enum": ["natural", "parallel", "choice"]
          }
        }
      },
      "then": {
        "required": ["children"]
      },
      "else": {
        "not": {
          "required": ["children"]
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "task"
          }
        }
      },
      "then": {
        "required": ["impacts"]
      },
      "else": {
        "not": {
          "required": ["impacts"]
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "nature"
          }
        }
      },
      "then": {
        "required": ["distribution"]
      },
      "else": {
        "not": {
          "required": ["distribution"]
        }
      }
    }
  ],
  "additionalProperties": false
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/nature_containing_choice.json
{
  "id": "104",
  "type": "nature",
  "label": "N5",
  "children": [
    {
      "id": "102",
      "type": "choice",
      "label": "C9",
      "children": [
        {
          "id": "100",
          "type": "task",
          "label": "T57",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "101",
          "type": "task",
          "label": "T58",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ],
      "max_delay": 0.0
    },
    {
      "id": "103",
      "type": "task",
      "label": "T59",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    }
  ],
  "distribution": [
    0.5,
    0.5
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/input_data/temp.json
{
  "id": "0",
  "label": "Parallel",
  "type": "parallel",
  "children": [
    {
      "id": "1",
      "label": "Sequential",
      "type": "sequential",
      "children": [
        {
          "id": "3",
          "label": "Task 3",
          "type": "task",
          "duration": 1,
          "impacts": [
            1,
            1
          ]
        },
        {
          "id": "4",
          "label": "Choice",
          "type": "choice",
          "children": [
            {
              "id": "5",
              "label": "Task 5",
              "type": "task",
              "duration": 1,
              "impacts": [
                1,
                1
              ]
            },
            {
              "id": "6",
              "label": "Task 6",
              "type": "task",
              "duration": 2,
              "impacts": [
                2,
                2
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "2",
      "label": "Task 2",
      "type": "task",
      "duration": 2,
      "impacts": [
        2,
        2
      ]
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/nature_containing_sequential.json
{
  "id": "149",
  "type": "nature",
  "label": "N9",
  "children": [
    {
      "id": "147",
      "type": "sequential",
      "children": [
        {
          "id": "145",
          "type": "task",
          "label": "T83",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "146",
          "type": "task",
          "label": "T84",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ]
    },
    {
      "id": "148",
      "type": "task",
      "label": "T85",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    }
  ],
  "distribution": [
    0.6,
    0.4
  ]
}
