=== danielamadori/Simulator-BPMN-CPI/docs/schemas/general/bpmn/region.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "region.schema.json",
  "title": "Region tree representing BPMN elements",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for region"
    },
    "type": {
      "type": "string",
      "enum": ["choice", "parallel", "sequence", "loop", "nature"]
    },
    "label": {
      "type": "string",
      "description": "Label for the region, used for display purposes."
    },
    "duration": {
      "type": "number",
      "description": "Duration associated with the region, if applicable."
    },
    "impacts": {
      "type": "array",
      "items": {
        "type": "number",
        "description": "Identifier of the impact associated with this region.",
        "minimum": 0
      },
      "description": "Vector of impacts associated with the region."
    },
    "children": {
      "type": "array",
      "items": { "$ref": "#" },
      "description": "List of child regions or tasks within this region."
    },
    "distribution": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      }
    }
  },
  "required": [
    "id",
    "type"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "enum": ["natural", "parallel", "choice"]
          }
        }
      },
      "then": {
        "required": ["children"]
      },
      "else": {
        "not": {
          "required": ["children"]
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "task"
          }
        }
      },
      "then": {
        "required": ["impacts"]
      },
      "else": {
        "not": {
          "required": ["impacts"]
        }
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "nature"
          }
        }
      },
      "then": {
        "required": ["distribution"]
      },
      "else": {
        "not": {
          "required": ["distribution"]
        }
      }
    }
  ],
  "additionalProperties": false
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/sequential_in_parallel.json
{
  "id": "74",
  "type": "parallel",
  "label": "P8",
  "children": [
    {
      "id": "70",
      "type": "sequential",
      "children": [
        {
          "id": "68",
          "type": "task",
          "label": "T40",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "69",
          "type": "task",
          "label": "T41",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ]
    },
    {
      "id": "73",
      "type": "sequential",
      "children": [
        {
          "id": "71",
          "type": "task",
          "label": "T42",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "72",
          "type": "task",
          "label": "T43",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ]
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/parallel_with_loop.json
{
  "id": "67",
  "type": "parallel",
  "label": "P7",
  "children": [
    {
      "id": "64",
      "type": "task",
      "label": "T38",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    },
    {
      "id": "66",
      "type": "loop",
      "label": "L4",
      "children": [
        {
          "id": "65",
          "type": "task",
          "label": "T39",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ],
      "distribution": 0.5,
      "bound": 5
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/input_data/bpmn_parallel.json
{
  "id": "2",
  "type": "parallel",
  "label": "Parallel 1",
  "children": [
    {
      "id": "8",
      "type": "task",
      "label": "Bending",
      "impacts": [
        20,
        1
      ],
      "duration": 1
    },
    {
      "id": "9",
      "type": "task",
      "label": "Heavy polishing",
      "impacts": [
        5,
        4
      ],
      "duration": 2
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/input_data/bpmn_choice.json
{
  "id": "1",
  "type": "choice",
  "label": "Choice painting",
  "children": [
    {
      "id": "14",
      "type": "task",
      "label": "HPHS painting",
      "impacts": [
        40,
        1
      ],
      "duration": 1
    },
    {
      "id": "15",
      "type": "task",
      "label": "LPLS painting",
      "impacts": [
        20,
        3
      ],
      "duration": 2
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/parallel_choice_simple.json
{
  "id": "56",
  "type": "parallel",
  "label": "P4",
  "children": [
    {
      "id": "54",
      "type": "choice",
      "label": "C4",
      "children": [
        {
          "id": "52",
          "type": "task",
          "label": "T31",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "53",
          "type": "task",
          "label": "T32",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ],
      "max_delay": 0.0
    },
    {
      "id": "55",
      "type": "task",
      "label": "T33",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    }
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/nature_containing_parallel.json
{
  "id": "99",
  "type": "nature",
  "label": "N4",
  "children": [
    {
      "id": "97",
      "type": "parallel",
      "label": "P10",
      "children": [
        {
          "id": "95",
          "type": "task",
          "label": "T54",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        },
        {
          "id": "96",
          "type": "task",
          "label": "T55",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ]
    },
    {
      "id": "98",
      "type": "task",
      "label": "T56",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    }
  ],
  "distribution": [
    0.6,
    0.4
  ]
}

=== danielamadori/Simulator-BPMN-CPI/tests/input_data/bpmn_nature.json
{
  "id": "6",
  "type": "nature",
  "label": "Nature polishing",
  "children": [
    {
      "id": "9",
      "type": "task",
      "label": "Heavy polishing",
      "impacts": [5, 4],
      "duration": 2
    },
    {
      "id": "10",
      "type": "task",
      "label": "Light polishing",
      "impacts": [8, 1],
      "duration": 1
    }
  ],
  "distribution": [0.2, 0.8]
}

=== danielamadori/Simulator-BPMN-CPI/tests/spin/output/nature_containing_loop.json
{
  "id": "108",
  "type": "nature",
  "label": "N6",
  "children": [
    {
      "id": "106",
      "type": "loop",
      "label": "L10",
      "children": [
        {
          "id": "105",
          "type": "task",
          "label": "T60",
          "duration": 1.0,
          "impacts": [
            1.0
          ]
        }
      ],
      "distribution": 0.5,
      "bound": 5
    },
    {
      "id": "107",
      "type": "task",
      "label": "T61",
      "duration": 1.0,
      "impacts": [
        1.0
      ]
    }
  ],
  "distribution": [
    0.7,
    0.3
  ]
}
